FROM paritytech/ci-linux:production as build

WORKDIR /code
COPY . .
RUN cargo build --release

FROM ubuntu:latest
WORKDIR /node

# Copy the node binary.
COPY --from=build /code/target/release/node-template .

# Install root certs, see: https://github.com/paritytech/substrate/issues/9984
# RUN apt update && \
#     apt install -y ca-certificates && \
#     update-ca-certificates && \
#     apt remove ca-certificates -y && \
#     rm -rf /var/lib/apt/lists/*

EXPOSE 9944
CMD [ "./node-template", "--dev" ]