
//! Autogenerated weights for `pallet_nft_marketplace`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-11-04, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `LAPTOP-DFFNONK6`, CPU: `11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: 1024

// Executed Command:
// ./target/release/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_nft_marketplace
// --extrinsic
// *
// --steps
// 50
// --repeat
// 20
// --output
// pallets/nft-marketplace/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn list_object() -> Weight;
	fn buy_nft() -> Weight;
}

/// Weight functions for `pallet_nft_marketplace`.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {

	/// Storage: `NftMarketplace::CollectionCount` (r:1 w:1)
	/// Proof: `NftMarketplace::CollectionCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:1)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionMetadataOf` (r:1 w:1)
	/// Proof: `Nfts::CollectionMetadataOf` (`max_values`: None, `max_size`: Some(5038), added: 7513, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:100 w:100)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:100 w:100)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemMetadataOf` (r:100 w:100)
	/// Proof: `Nfts::ItemMetadataOf` (`max_values`: None, `max_size`: Some(5091), added: 7566, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::ListedNftsOfCollection` (r:1 w:1)
	/// Proof: `NftMarketplace::ListedNftsOfCollection` (`max_values`: None, `max_size`: Some(414), added: 2889, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::ListedNfts` (r:1 w:1)
	/// Proof: `NftMarketplace::ListedNfts` (`max_values`: Some(1), `max_size`: Some(2400004), added: 2400499, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::SellerListings` (r:1 w:1)
	/// Proof: `NftMarketplace::SellerListings` (`max_values`: None, `max_size`: Some(2400044), added: 2402519, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionRoleOf` (r:0 w:1)
	/// Proof: `Nfts::CollectionRoleOf` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:0 w:1)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:100)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionAccount` (r:0 w:1)
	/// Proof: `Nfts::CollectionAccount` (`max_values`: None, `max_size`: Some(68), added: 2543, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::OngoingNftDetails` (r:0 w:100)
	/// Proof: `NftMarketplace::OngoingNftDetails` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	fn list_object() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `79`
		//  Estimated: `2403509`
		// Minimum execution time: 7_527_271_000 picoseconds.
		Weight::from_parts(7_881_033_000, 0)
			.saturating_add(Weight::from_parts(0, 2403509))
			.saturating_add(T::DbWeight::get().reads(306))
			.saturating_add(T::DbWeight::get().writes(509))
	}
	/// Storage: `NftMarketplace::ListedNftsOfCollection` (r:1 w:1)
	/// Proof: `NftMarketplace::ListedNftsOfCollection` (`max_values`: None, `max_size`: Some(414), added: 2889, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::OngoingNftDetails` (r:100 w:100)
	/// Proof: `NftMarketplace::OngoingNftDetails` (`max_values`: None, `max_size`: Some(105), added: 2580, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::SoldNftsCollection` (r:1 w:1)
	/// Proof: `NftMarketplace::SoldNftsCollection` (`max_values`: None, `max_size`: Some(414), added: 2889, mode: `MaxEncodedLen`)
	/// Storage: `System::Account` (r:1 w:1)
	/// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::ListedNfts` (r:1 w:1)
	/// Proof: `NftMarketplace::ListedNfts` (`max_values`: Some(1), `max_size`: Some(2400004), added: 2400499, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::SellerListings` (r:1 w:1)
	/// Proof: `NftMarketplace::SellerListings` (`max_values`: None, `max_size`: Some(2400044), added: 2402519, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Collection` (r:1 w:0)
	/// Proof: `Nfts::Collection` (`max_values`: None, `max_size`: Some(84), added: 2559, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Attribute` (r:99 w:0)
	/// Proof: `Nfts::Attribute` (`max_values`: None, `max_size`: Some(446), added: 2921, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::CollectionConfigOf` (r:1 w:0)
	/// Proof: `Nfts::CollectionConfigOf` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemConfigOf` (r:99 w:0)
	/// Proof: `Nfts::ItemConfigOf` (`max_values`: None, `max_size`: Some(48), added: 2523, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Item` (r:99 w:99)
	/// Proof: `Nfts::Item` (`max_values`: None, `max_size`: Some(861), added: 3336, mode: `MaxEncodedLen`)
	/// Storage: `NftMarketplace::SellerSoldNfts` (r:1 w:1)
	/// Proof: `NftMarketplace::SellerSoldNfts` (`max_values`: None, `max_size`: Some(2400044), added: 2402519, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::Account` (r:0 w:198)
	/// Proof: `Nfts::Account` (`max_values`: None, `max_size`: Some(88), added: 2563, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::ItemPriceOf` (r:0 w:99)
	/// Proof: `Nfts::ItemPriceOf` (`max_values`: None, `max_size`: Some(89), added: 2564, mode: `MaxEncodedLen`)
	/// Storage: `Nfts::PendingSwapOf` (r:0 w:99)
	/// Proof: `Nfts::PendingSwapOf` (`max_values`: None, `max_size`: Some(71), added: 2546, mode: `MaxEncodedLen`)
	fn buy_nft() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `27983`
		//  Estimated: `2403509`
		// Minimum execution time: 10_320_036_000 picoseconds.
		Weight::from_parts(10_682_896_000, 0)
			.saturating_add(Weight::from_parts(0, 2403509))
			.saturating_add(T::DbWeight::get().reads(405))
			.saturating_add(T::DbWeight::get().writes(601))
	}
}
